platform :ios, '10.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'))
  unless File.exist?(generated_xcode_build_settings_path)
    raise 'Generated.xcconfig must exist. Please run "flutter pub get" first.'
  end
  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise 'FLUTTER_ROOT not found in Generated.xcconfig. Please run "flutter pub get" first.'
end

flutter_directory = File.expand_path(File.join(flutter_root, 'packages', 'flutter_tools', 'bin'))
flutter_podhelper = File.join(flutter_directory, 'podhelper.rb')
require File.expand_path(flutter_podhelper, __FILE__)

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have enabled Flipper in your project, you should
  # comment the next line to disable it.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
